### PR TITLE
apostrophe

### PR DESCRIPTION
**Pull request by sghill**
leroy jenkins reference was using quote instead of apostrophe :)

### CODE REVIEW

**Comment by steveklabnik** [comment]
It's part of the joke, holding down shift the entire time. ;)

**Comment by steveklabnik** [comment]
That said, maybe it's not clear... Thanks! :)

**Comment by sghill** [comment]
D'oh! Oh well, I'll still chalk up getting a silly commit pulled into a steveklabnik joint as a victory. Thanks! :)

**Comment by steveklabnik** [comment]
It is! :D Humor is hard on the internet.

**Comment by denisdefreyne** [comment]
zomg.

**Comment by steveklabnik** [comment]
This is now in production. :heart: :confetti_ball: :+1:

**Pull request merged**
