### PR TITLE
Features/public scopes

### PR DESCRIPTION
**Pull request by richo**
So I wanted to use issue2pr for transmuting a thing, but I'm always super iffy about granting private scopes to things because I have access to lots of private things.

I added a second auth url that only grants public scopes to issue2pr, thereby making people like myself way less paranoid.

### CODE REVIEW

**Comment by richo** [comment]
ping!

**Comment by stephenmathieson** [comment]
+1

**Comment by steveklabnik** [comment]
Hey this seems good, thank you!

**Comment by richo** [comment]
Heh. Aaaand it's broken on the live site. It seemed to do the right thing for me in dev, I'll see if I can work out why it's broken.

**Comment by steveklabnik** [comment]
oops. Any ideas?

**Pull request merged**
